### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [xplrz/daretofork#1]
* [ ] write a "contributor manifesto".
* [ ] write a "contributor-friendly organization manifesto".
* [ ] list suggestions to improve contributions, i.e., CONTRIBUTING.md files etc.
* [ ] start an "awesome-contribution" repo with guides and good practices.
* [ ] setup a "daretofork-acme-demo" repo w/ good practices and examples.
* [ ] setup a website to explain everything.
* [ ] setup a dashboard to list available contributions with filters.
* [ ] setup automatic markdown badges (self-updating) for repos.
* [ ] setup automatic markdown badges (self-updating) for contributors, with stats.
* [ ] setup a logo that people can proudly use on their website/README.md to endorse the project and show they invest energy in being contributor-friendly.
* [ ] bootstrap a github bot to comment on issues/PRs if PR author and/or targeted repositories to ease the process and create a welcoming environment.
* [ ] define a github.com/$USER/.daretofork meta repo or equivalent to automatically detect some info like the languages and if the contributor belongs to a school.
* [ ] if the user belongs to a school, configure the comment bot to ask more questions to the reviewers, and generate reports for schools.
* [ ] avatar creator -> append a "daretofork apprentice/poweruser" to an avatar" a-la linkedin's open to work.
* [ ] badge creator for github profile with points.
* [ ] joint venture w/ pathwar.
* [ ] joint venture w/ depviz.
* [ ] joint venture w/ gno (contract).
* [ ] certification program and coaching for organizations to become daretofork friendly and improve their OSS presence.
